const defaultConfig = {
  fgColor: '0 1 0',
  bgColor: '0 0 0',
  stColor: '0.9 1 0.9',
  chars: 'katakana',
  randomChars: 'true',
  font: 'Consolas',
  centerText: '',
  centerFont: 'Hacked, sans-serif',
  centerColor: '0 0.75 0',
  centerSize: 1,
  changeFreq: 100,
  size: 30,
  edgeBlur: 160,
  charBlur: 0,
  showFps: false,
  parallax: true,
  maxLines: 30,
  maxLineSpeed: 10,
  minLineLength: 1,
  maxLineLength: 1,
  speed: 20,
  special: false
};
let config = defaultConfig;
